### ISSUE TITLE
Option to include popup windows

### ISSUE THREAD

**Issue by luckman212** [fthdgn/chrome_organize_windows_tabs#1]
Great extension! 👏

I noticed in the [last commit 196abb9](https://github.com/fthdgn/chrome_organize_windows_tabs/commit/196abb90789ed33d0297545a6322766a45d471cd) you changed the behavior to exclude all popup windows. Would you consider making this an option instead?

**Comment by fthdgn** [comment]
Yes. I can add an option just like pinned tabs.

I ignored them because I didn't want to convert chrome app windows to tabs.

**Comment by fthdgn** [comment]
1.3.0 version is released with the option. You can disable "Ignore popup windows for merge and sort actions" from the options menu of the extension.
